TicketsAereosBSI_JSF/src/main/java/br/pucpr/ticketsAereos/view/mb/ManterCiaAereaMB.java
package br.pucpr.ticketsAereos.view.mb;

import static br.pucpr.ticketsAereos.view.mb.PesquisarCiaAereaMB.CIAAEREA_SELECIONADA;
import static br.pucpr.ticketsAereos.view.mb.PesquisarCiaAereaMB.FILTRO_PESQUISA;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.log4j.Logger;

import br.pucpr.ticketsAereos.bc.CiaAereaBC;
import br.pucpr.ticketsAereos.dto.CiaAereaDTO;
import br.pucpr.ticketsAereos.exception.BSIException;
import br.pucpr.ticketsAereos.model.CiaAerea;
import br.pucpr.ticketsAereos.view.mb.utils.ViewUtil;
import br.pucpr.ticketsAereos.view.messages.MessagesUtils;

/**
 * @author Everson Mauda
 * @version 1.0.0
 */

@ManagedBean
@ViewScoped
public class ManterCiaAereaMB implements Serializable{
	
	public enum Acoes {
		EDITAR, EXCLUIR, INCLUIR, VISUALIZAR;
	}
	
	/////////////////////////////////////
	// Atributos
	/////////////////////////////////////
	
	private static final long serialVersionUID = 1L;
	
	//Utilizado para logs via Log4J
	private static Logger log = Logger.getLogger(ManterCiaAereaMB.class);
	
	private CiaAerea ciaAerea = new CiaAerea();
	private CiaAereaDTO filtroPesquisa;
	
	private Acoes acao = Acoes.INCLUIR;
	
	/////////////////////////////////////
	// Construtores
	/////////////////////////////////////
	
	public ManterCiaAereaMB() {
	}
	
	@PostConstruct
	private void init(){
		acao = (Acoes) ViewUtil.getParameter(Acoes.class);
		if(acao != null && !Acoes.INCLUIR.equals(acao)){
			ciaAerea = (CiaAerea) ViewUtil.getParameter(CIAAEREA_SELECIONADA);
			if(ciaAerea == null){
				throw new BSIException("ER0052");
			}
			log.debug("Valor do CiaAerea:" + ciaAerea);
			filtroPesquisa = (CiaAereaDTO) ViewUtil.getParameter(FILTRO_PESQUISA);
			log.debug("Valor do Filtro:" + filtroPesquisa);
		} else  {
			acao = Acoes.INCLUIR;
		}
	}	
	
	/////////////////////////////////////
	// Actions
	/////////////////////////////////////
	
	
	//Action de Salvar Usuario
	public String salvar() {
		if(isAcaoIncluir()){
			CiaAereaBC.getInstance().insert(this.ciaAerea);
		} else if(isAcaoEditar()){
			CiaAereaBC.getInstance().update(this.ciaAerea);
		} else if(isAcaoExcluir()){
			CiaAereaBC.getInstance().delete(this.ciaAerea);
		}
		MessagesUtils.addInfo("sucesso", "IN0000");
		return voltar();
	}
	
	public String voltar(){
		ViewUtil.setRequestParameter(FILTRO_PESQUISA, filtroPesquisa);
		return "pesquisarCiaAerea";
	}
	
	//Action para reset do cadastro
	public void limpar() {
		ciaAerea = new CiaAerea();
	}
	
	/////////////////////////////////////
	// Metodos Utilitarios
	/////////////////////////////////////
	
	public boolean isAcaoEditar(){
		return Acoes.EDITAR.equals(acao);
	}
	
	public boolean isAcaoExcluir(){
		return Acoes.EXCLUIR.equals(acao);
	}	
	
	public boolean isAcaoIncluir(){
		return Acoes.INCLUIR.equals(acao);
	}

	public boolean isAcaoVisualizar(){
		return Acoes.VISUALIZAR.equals(acao);
	}
	
	/////////////////////////////////////
	// Getters and Setters
	/////////////////////////////////////
	
	public CiaAerea getCiaAerea() {
		return ciaAerea;
	}
	
	public void setAviao(CiaAerea aviao) {
		this.ciaAerea = aviao;
	}
	
	public void setAcao(Acoes acao) {
		this.acao = acao;
	}
	
	public String getTitle(){
		switch(acao){
			case EDITAR:
				return MessagesUtils.getLabel("editarCiaAerea");
			case EXCLUIR:
				return MessagesUtils.getLabel("excluirCiaAerea");
			case INCLUIR:
				return MessagesUtils.getLabel("incluirCiaAerea");
			case VISUALIZAR:
				return MessagesUtils.getLabel("visualizarCiaAerea");
		}
		return null;
	}
}

TicketsAereosBSI_JSF/src/main/webapp/paginas/manterCiaAerea.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="centerContent">
		<h:form>
			<p:panel>
				<f:facet name="header">
					<h1>
						<h:outputText value="#{manterCiaAereaMB.title}" />
					</h1>
				</f:facet>
				<p:panelGrid columns="2" columnClasses="labelField, textField">
					<h:outputLabel for="codigo" value="#{msg['nome']}:" />
					<p:inputText id="codigo" value="#{manterCiaAereaMB.ciaAerea.nome}"
						disabled="#{manterCiaAereaMB.acaoVisualizar}" />
				</p:panelGrid>

				<f:facet name="footer">
					<p:panel toggleTitle="#{msg['acoes']}" styleClass="noBorder">
						<p:commandButton id="submit" value="#{msg['salvar']}"
								action="#{manterCiaAereaMB.salvar}" ajax="false"
								rendered="#{not manterCiaAereaMB.acaoVisualizar}" />
							
						<p:commandButton id="reset" value="#{msg['voltar']}"
								action="#{manterCiaAereaMB.voltar}" ajax="false" />
					</p:panel>
				</f:facet>
			</p:panel>
		</h:form>
	</ui:define>
</ui:composition>

TicketsAereosBSI_JSF/src/main/webapp/paginas/pesquisarCiaAerea.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/WEB-INF/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="centerContent">
		<h:form>
			<p:panel>
				<f:facet name="header">
					<h1>#{msg['pesquisarCiaAerea']}</h1>
				</f:facet>
				<p:panel toggleable="true" toggleSpeed="500">
						<f:facet name="header">
							#{msg['filtroPesquisa']}
						</f:facet>
					<p:panelGrid columns="4" columnClasses="labelField, textField, labelField, textField">
						<h:outputLabel for="codigo" value="#{msg['nome']}:"/>
						<p:inputText id="codigo" value="#{pesquisarCiaAereaMB.filtroPesquisa.nome}" />
					</p:panelGrid>
				
					<p:panel styleClass="noBorder">
						<p:commandButton value="#{msg['pesquisar']}"
							action="#{pesquisarCiaAereaMB.pesquisar}" update="resultados" />
					</p:panel>
				</p:panel>

				<p:spacer height="25px"/>

				<p:panel id="resultados" styleClass="noBorder">
					<p:dataTable value="#{pesquisarCiaAereaMB.ciaAereas}" var="ciaAerea"
							rendered="#{not empty pesquisarCiaAereaMB.ciaAereas}"
							selectionMode="single"
							selection="#{pesquisarCiaAereaMB.ciaAereaSelecionada}"
							rowKey="#{ciaAerea.id}">
						
						<f:facet name="header">
							#{msg['resultados']}
						</f:facet>

						<p:column headerText="#{msg['nome']}">
							#{ciaAerea.nome}
						</p:column>

						<f:facet name="footer">
							<p:commandButton value="#{msg['editar']}"
								action="#{pesquisarCiaAereaMB.editar}" ajax="false" />
							<p:commandButton value="#{msg['excluir']}"
								action="#{pesquisarCiaAereaMB.excluir}" ajax="false" />
							<p:commandButton value="#{msg['visualizar']}"
								action="#{pesquisarCiaAereaMB.visualizar}" ajax="false" />
						</f:facet>
					</p:dataTable>
				</p:panel>
			</p:panel>
		</h:form>
	</ui:define>
</ui:composition>